const Strings = {
  hello: 'Hello',
  welcomeToLafyuu: 'Welcome to Lafyuu',
  signInToContinue: 'Sign in to continue',
  yourEmail: 'Your Email',
  password: 'Password',
  signIn: 'Sign In',
  or: 'OR',
  loginWithGoogle: 'Login with Google',
  loginWithFacebook: 'Login with facebook',
  weight: 'Weight',
  warranty: 'Warranty',
  availability: 'Availability',
  returnPolicy: 'Return Policy',
  forgotPassword: 'Forgot Password?',
  dontHaveAnAccount: 'Don’t have a account?',
  register: 'Register',
  oopsYourPasswordIsNotCorrect: 'Oops! Your Password Is Not Correct',
  letsGetStarted: 'Let’s Get Started',
  createANewAccount: 'Create an new account',
  fullName: 'Full Name',
  yourEmailCreate: 'Your Email',
  passwordAgain: 'Password Again',
  haveAnAccount: 'have a account?',
  searchProduct: 'Search Product',
  category: 'Category',
  moreCategory: 'More Category',
  recommendedProduct: 'Recommended Product',
  weRecommendTheBestForYou: 'We recommend the best for you',
  home: 'Home',
  explore: 'Explore',
  cart: 'Cart',
  offer: 'Offer',
  account: 'Account',
  favoriteProduct: 'Favorite Product',
  writeReview: 'Write Review',
  pleaseWriteOverallLevelOfSatisfactionWithYourShippingDeliveryService:
    'Please write Overall level of satisfaction with your shipping / Delivery Service',
  writeYourReview: 'Write Your Review',
  writeYourReviewHere: 'Write your review here',
  addPhoto: 'Add Photo',
  selectSize: 'Select Size',
  selectColor: 'Select Color',
  specification: 'Specification',
  shown: 'Shown',
  reviewProduct: 'Review Product',
  seeMore: 'See More',
  youMightAlsoLike: 'You Might Also Like',
  addToCart: 'Add To Cart',
  removeFromCart: 'Remove From Cart',
  removeFromWishlist: 'Remove From Wishlist',
  moveToWishlist: 'Move To Wishlist',
  notification: 'Notification',
  feed: 'Feed',
  activity: 'Activity',
  productNotFound: 'Product Not Found',
  productDetail: 'Product Details',
  thankYouForShoppingUsingLafyuu: 'thank you for shopping using lafyuu',
  backToHome: 'Back to Home',
  sortBy: 'Sort By',
  style: 'Style',
  bestMatch: 'Best Match',
  timeEndingSoonest: 'Time: ending soonest',
  timeNewlyListed: 'Time: newly listed',
  priceShippingLowestFirst: 'Price + Shipping: lowest first',
  priceShippingHighestFirst: 'Price + Shipping: highest first',
  distanceNearestFirst: 'Distance: nearest first',
  filterSearch: 'Filter Search',
  priceRange: 'Price Range',
  min: 'MIN',
  max: 'MAX',
  condition: 'Condition',
  new: 'New',
  used: 'Used',
  notSpecified: 'Not Specified',
  buyingFormat: 'Buying Format',
  allListings: 'All Listings',
  acceptsOffers: 'Accepts Offers',
  auction: 'Auction',
  buyItNow: 'Buy It Now',
  classifiedAds: 'Classified Ads',
  itemLocation: 'Item Location',
  usOnly: 'US Only',
  northAmerica: 'North America',
  europe: 'Europe',
  asia: 'Asia',
  showOnly: 'Show Only',
  freeReturns: 'Free Returns',
  returnsAccepted: 'Returns Accepted',
  authorizedSeller: 'Authorized Seller',
  completedItems: 'Completed Items',
  soldItems: 'Sold Items',
  dealsSavings: 'Deals & Savings',
  saleItems: 'Sale Items',
  listedAsLots: 'Listed as Lots',
  searchInDescription: 'Search in Description',
  benefitsCharity: 'Benefits charity',
  authenticityVerified: 'Authenticity Verified',
  apply: 'Apply',
  yourCart: 'Your Cart',
  enterCouponCode: 'Enter Cupon Code',
  items: 'Items',
  shipping: 'Shipping',
  importCharges: 'Import charges',
  totalPrice: 'Total Price',
  checkOut: 'Check Out',
  shipTo: 'Ship To',
  edit: 'Edit',
  next: 'Next',
  payment: 'Payment',
  creditCardOrDebit: 'Credit Card Or Debit',
  paypal: 'Paypal',
  bankTransfer: 'Bank Transfer',
  cashOnDelivery: 'Cash On Delivery',
  chooseCard: 'Choose Card',
  pay: 'Pay',
  success: 'Success',
  backToOrder: 'Back To Order',
  profile: 'Profile',
  order: 'Order',
  address: 'Address',
  gender: 'Gender',
  birthday: 'Birthday',
  email: 'Email',
  phoneNumber: 'Phone Number',
  name: 'Name',
  firstName: 'First Name',
  lastName: 'Last Name',
  chooseGender: 'Choose Gender',
  male: 'Male',
  female: 'Female',
  other: 'Other',
  yourBirthday: 'Your Birthday',
  changePassword: 'Change Password',
  oldPassword: 'Old Password',
  newPassword: 'New Password',
  newPasswordAgain: 'New Password Again',
  orderDetails: 'Order Details',
  packing: 'Packing',
  shippingDetails: 'Shipping',
  dateShipping: 'Date Shipping',
  paymentDetails: 'Payment Details',
  changeEmail: 'Change Email',
  weWillSendVerificationToYourNewEmail:
    'We Will Send verification to your New Email',
  countryOrRegion: 'Country or region',
  streetAddress: 'Street Address',
  streetAddress2Optional: 'Street Address 2 (Optional)',
  city: 'City',
  stateProvinceRegion: 'State/Province/Region',
  zipCode: 'Zip Code',
  phoneNumberAddress: 'Phone Number',
  confirmation: 'Confirmation',
  areYouSureWannaDeleteAddress: 'Are you sure wanna delete address',
  delete: 'Delete',
  cancel: 'Cancel',
  pleaseWait: 'Please Wait',
};

export default Strings;
